#-------------实验设置-------------
EXPERIMENT_NAME: cifar100  # 实验名称
LOG_DIR: runs  # 实验保存路径
LOG_VERBOSE: false  # 记录冗长的模型参数信息
# ------------数据集---------------
TRAIN_DATASET: E:\Dataset\cifar100\train.txt  # 训练集
TEST_DATASET: E:\Dataset\cifar100\test.txt  # 测试集
#------------训练参数--------------
DATASET_TASK: ClassifyDataset  # 数据加载函数
IMAGE_SIZE: [224,224] # 训练图片尺寸
EPOCH: 100
TRAIN_BATCH_SIZE: 128  # DDP模式下为所有卡上batch-size的总和
TEST_BATCH_SIZE: 64  # DDP模式下为所有卡上batch-size的总和，通常取TRAIN_BATCH_SIZE的一半
NUM_WORKERS: 8
MODEL_NAME: repvgg  # 网络模型
INITIALIZE_WEIGHTS: Kaiming_Initialize  # 网络权重初始化方式, null为不使用
DEVICE: "1"  # 指定设备'cpu' or '0' or '0,1,2,3'
LOSS_FUNCTION: LabelSmoothingLoss  # 损失函数
OPTIMIZER: Adam  # 优化器
SCHEDULER: CosineAnnealingLR  # 学习率优化
EVALUATE_FUNCTION: ClassifyEvaluate # 对模型进行精度验证的函数
TRAINING_FUNCTION: ClassifyTrain  # 对模型进行训练的函数
KEEP_SAVE: 0  # 持续保存第i个epoch后的所有模型，0为不保存
INTERVAL_SAVE: 0  # 每隔i个epoch保存一次，0为不保存
WARMUP: 0  # 模型预热训练多少个epoch
COLOR_AUGMNET: 1.0  # 色彩增强概率
FLIP_TD: 0.0  # 上下翻转概率
FLIP_LR: 0.5  # 左右翻转概率
ROTATION: null  # 旋转+/-角度，null为不旋转
MixUp: 0.0  # 进行mixup增强
LABEL_SMOOTH: 0.1  # 标签平滑, null为不设置
LABEL_INDEX_NAME:  # 标签类别名称索引
    [
      apple,
      aquarium_fish,
      baby,
      bear,
      beaver,
      bed,
      bee,
      beetle,
      bicycle,
      bottle,
      bowl,
      boy,
      bridge,
      bus,
      butterfly,
      camel,
      can,
      castle,
      caterpillar,
      cattle,
      chair,
      chimpanzee,
      clock,
      cloud,
      cockroach,
      couch,
      crab,
      crocodile,
      cup,
      dinosaur,
      dolphin,
      elephant,
      flatfish,
      forest,
      fox,
      girl,
      hamster,
      house,
      kangaroo,
      keyboard,
      lamp,
      lawn_mower,
      leopard,
      lion,
      lizard,
      lobster,
      man,
      maple_tree,
      motorcycle,
      mountain,
      mouse,
      mushroom,
      oak_tree,
      orange,
      orchid,
      otter,
      palm_tree,
      pear,
      pickup_truck,
      pine_tree,
      plain,
      plate,
      poppy,
      porcupine,
      possum,
      rabbit,
      raccoon,
      ray,
      road,
      rocket,
      rose,
      sea,
      seal,
      shark,
      shrew,
      skunk,
      skyscraper,
      snail,
      snake,
      spider,
      squirrel,
      streetcar,
      sunflower,
      sweet_pepper,
      table,
      tank,
      telephone,
      television,
      tiger,
      tractor,
      train,
      trout,
      tulip,
      turtle,
      wardrobe,
      whale,
      willow_tree,
      wolf,
      woman,
      worm
    ]
#------------指定模型的具体参数--------------
MODEL_NAME_PARAM:
    repvgg:
        category: 100  # 训练类别
        activations: softmax  # 网络最后一层（softmax，sigmoid），null为Identity()
#------------指定训练epoch的具体参数--------------
TRAINING_FUNCTION_PARAM:
    ClassifyTrain:
        AMP: true  # 自动混合精度，只能在cuda上使用
#------------指定权重初始化的具体参数--------------
INITIALIZE_WEIGHTS_PARAM:
    Kaiming_Initialize:
#------------指定损失函数的具体参数--------------
LOSS_FUNCTION_PARAM:
    LabelSmoothingLoss:
#------------指定优化器的具体参数--------------
OPTIMIZER_PARAM:
    SGD:
        lr: 0.01  # 初始学习率
        momentum: 0.937
        weight_decay: 0.0
    Adam:
        lr: 0.001  # 初始学习率
        momentum1: 0.937
        momentum2: 0.999
        weight_decay: 0
#------------指定scheduler的具体参数--------------
SCHEDULER_PARAM:
    MultiStepLR:
        milestones: [30,60,90]  # 第i个epoch的时候调整一次学习率（不含warmup次数）
        gamma: 0.1  # 衰减因子
    CosineAnnealingLR:
        T_max: 100  # cos半个周期需要迭代的epoch数
        eta_min: 0.00001  # 最小学习率
    ExponentialLR:
        gamma: 0.9  # 根据epoch呈指数衰减时的底数
    LinearLR:
        step: 3  # 在多个少epoch内衰减
        lrf: 0.01  # 在step内学习率系数从1衰减到该值
    CosineHalfPeriodLR:
        epoch: 100 # 在多个少epoch内衰减
#------------指定精度验证的具体参数--------------
EVALUATE_FUNCTION_PARAM:
    ClassifyEvaluate: